//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCLG
    {
        public int Id { get; set; }
        public string JOB_PHASE_CC { get; set; }
        public string JOB { get; set; }
        public string SUB_JOB { get; set; }
        public string PHASE { get; set; }
        public string COST_CODE { get; set; }
        public string EWO { get; set; }
        public string DESCRIPTION { get; set; }
        public string CLIENT_PO { get; set; }
        public string EXTRA { get; set; }
        public string WORK_ORDER { get; set; }
    }
}
